
export const ImagePath = {
    splashscreen: require('../assets/images/Splashscreen.png'),
    splashscreenlogo: require('../assets/images/splashscreenlogo.png'),
    eAmata: require('../assets/images/eAmata.png'),
    eAMataBlueText : require('../assets/images/eAMataBlueText.png'),
    rafiki : require('../assets/images/rafiki.png'),
    resetpass : require('../assets/images/resetpass.png'),
    loader : require('../assets/images/circular-determinate.png'),
    ecg_heart : require('../assets/images/ecg_heart.png'),
    ecg_heart_focused : require('../assets/images/ecg_heart_focused.png'),
    event : require('../assets/images/event.png'),
    event_focused : require('../assets/images/event_focused.png'),  
    avatar : require('../assets/images/Avatar.png'),  
    browse_activity : require('../assets/images/browse_activity.png'), 
    clinical_notes : require('../assets/images/clinical_notes.png'),  
    handshake : require('../assets/images/handshake.png'),    
    allergies : require('../assets/images/allergies.png'),    
    medication_liquid : require('../assets/images/medication_liquid.png'),    
    cardiology : require('../assets/images/cardiology.png'),    
    glucose : require('../assets/images/glucose.png'),    
    water_drop : require('../assets/images/water_drop.png'),    
    weight : require('../assets/images/weight.png'),    
}